FROM rockylinux/rockylinux:8

ARG OOD_VERSION
ARG OOD_MAJOR_MINOR

LABEL maintainer="travert@osc.edu"
LABEL ood.version="${OOD_VERSION}"
LABEL ood.distro="el8"
LABEL ood.scan="staging"

# Rocky 8: needs powertools + dnf-plugins-core for config-manager
RUN OOD_MM_RE="$(printf '%s' "$OOD_MAJOR_MINOR" | sed 's/\./\\./g')" && \
    dnf -y install dnf-plugins-core epel-release && \
    dnf config-manager --set-enabled powertools && \
    dnf -y install "https://yum.osc.edu/ondemand/staging/${OOD_MAJOR_MINOR}/ondemand-release-web-${OOD_MAJOR_MINOR}-1.el8.noarch.rpm" && \
    sed -i "s|ondemand/${OOD_MM_RE}/|ondemand/staging/${OOD_MM_RE}/|g" /etc/yum.repos.d/ondemand-web.repo && \
    dnf module enable -y ruby:3.3 nodejs:22 && \
    dnf -y install "ondemand-${OOD_VERSION}" && \
    dnf clean all && \
    rm -rf /var/cache/dnf/*
