FROM amazonlinux:2023
LABEL maintainer="travert@osc.edu"
LABEL ood.version="4.2.2"
LABEL ood.distro="amzn2023"
LABEL ood.scan="staging"

# Amazon Linux 2023: no dnf modules; ondemand-ruby/nodejs handle their own deps
RUN dnf -y install https://yum.osc.edu/ondemand/staging/4.2/ondemand-release-web-4.2-1.amzn2023.noarch.rpm && \
    sed -i 's|ondemand/4\.2/|ondemand/staging/4.2/|g' /etc/yum.repos.d/ondemand-web.repo && \
    dnf -y install ondemand && \
    dnf clean all && \
    rm -rf /var/cache/dnf/*
