FROM rockylinux/rockylinux:9

ARG OOD_VERSION
ARG OOD_MAJOR_MINOR

LABEL maintainer="travert@osc.edu"
LABEL ood.version="${OOD_VERSION}"
LABEL ood.distro="el9"
LABEL ood.scan="staging"

RUN OOD_MM_RE="$(printf '%s' "$OOD_MAJOR_MINOR" | sed 's/\./\\./g')" && \
    dnf -y install "https://yum.osc.edu/ondemand/staging/${OOD_MAJOR_MINOR}/ondemand-release-web-${OOD_MAJOR_MINOR}-1.el9.noarch.rpm" && \
    sed -i "s|ondemand/${OOD_MM_RE}/|ondemand/staging/${OOD_MM_RE}/|g" /etc/yum.repos.d/ondemand-web.repo && \
    dnf -y install epel-release && \
    dnf module enable -y ruby:3.3 nodejs:22 && \
    dnf -y install "ondemand-${OOD_VERSION}" && \
    dnf clean all && \
    rm -rf /var/cache/dnf/*
